version: '3.7'

services:
  pg:
    image: bitnami/postgresql:latest
    container_name: pg-finances
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=finances
    volumes:
      - ./data/pg:/data/postgres


  
